import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Consolidated initial schema for SQLite (Electron mode).
 * Equivalent to all 34 PostgreSQL migrations merged into one.
 * SQLite does not support ENUM types — text columns with CHECK constraints are used instead.
 * UUIDs are generated by TypeORM at the application layer (no gen_random_uuid()).
 */
export class InitialSchema00000000000001 implements MigrationInterface {
  name = 'InitialSchema00000000000001';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // Enable WAL mode for better concurrent read performance from tablet kiosk requests.
    await queryRunner.query(`PRAGMA journal_mode=WAL`);
    await queryRunner.query(`PRAGMA busy_timeout=5000`);
    await queryRunner.query(`PRAGMA foreign_keys=ON`);

    await queryRunner.query(`
      CREATE TABLE "operators" (
        "id"            VARCHAR(36)   NOT NULL,
        "username"      VARCHAR(100)  NOT NULL,
        "password_hash" VARCHAR(255)  NOT NULL,
        "display_name"  VARCHAR(200)  NOT NULL,
        "role"          VARCHAR(20)   NOT NULL DEFAULT 'operator'
                        CHECK("role" IN ('admin', 'operator', 'cashier')),
        "zone"          VARCHAR(100),
        "is_active"     INTEGER       NOT NULL DEFAULT 1,
        "created_at"    DATETIME      NOT NULL DEFAULT (datetime('now')),
        "updated_at"    DATETIME      NOT NULL DEFAULT (datetime('now')),
        CONSTRAINT "PK_operators_id" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_operators_username" UNIQUE ("username")
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "users" (
        "id"                           VARCHAR(36)   NOT NULL,
        "legacy_id"                    VARCHAR(100),
        "name"                         VARCHAR(200)  NOT NULL,
        "zone"                         VARCHAR(100),
        "cell"                         VARCHAR(100),
        "normalized_cell"              VARCHAR(100),
        "cell_normalization_version"   INTEGER       NOT NULL DEFAULT 0,
        "date_of_birth"                VARCHAR(20),
        "hometown"                     VARCHAR(500),
        "offense"                      VARCHAR(500),
        "arrest_date"                  VARCHAR(20),
        "detention_status"             VARCHAR(100),
        "is_active"                    INTEGER       NOT NULL DEFAULT 1,
        "source"                       VARCHAR(50),
        "synced_at"                    DATETIME,
        "created_at"                   DATETIME      NOT NULL DEFAULT (datetime('now')),
        "updated_at"                   DATETIME      NOT NULL DEFAULT (datetime('now')),
        CONSTRAINT "PK_users_id" PRIMARY KEY ("id")
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "prisoner_accounts" (
        "id"         VARCHAR(36)    NOT NULL,
        "user_id"    VARCHAR(36)    NOT NULL UNIQUE,
        "balance"    REAL           NOT NULL DEFAULT 0,
        "created_at" DATETIME       NOT NULL DEFAULT (datetime('now')),
        "updated_at" DATETIME       NOT NULL DEFAULT (datetime('now')),
        CONSTRAINT "PK_prisoner_accounts_id" PRIMARY KEY ("id"),
        CONSTRAINT "FK_prisoner_accounts_user" FOREIGN KEY ("user_id")
          REFERENCES "users"("id") ON DELETE CASCADE
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "account_transactions" (
        "id"               VARCHAR(36)  NOT NULL,
        "user_id"          VARCHAR(36)  NOT NULL,
        "type"             VARCHAR(20)  NOT NULL
                           CHECK("type" IN ('topup', 'payment', 'refund', 'adjustment')),
        "amount"           REAL         NOT NULL,
        "balance_after"    REAL         NOT NULL,
        "method"           VARCHAR(50),
        "ref"              VARCHAR(255),
        "related_order_id" VARCHAR(36),
        "operator_id"      VARCHAR(36),
        "note"             TEXT,
        "created_at"       DATETIME     NOT NULL DEFAULT (datetime('now')),
        CONSTRAINT "PK_account_transactions_id" PRIMARY KEY ("id"),
        CONSTRAINT "FK_account_transactions_user" FOREIGN KEY ("user_id")
          REFERENCES "users"("id") ON DELETE CASCADE
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "menu_items" (
        "id"         VARCHAR(36)   NOT NULL,
        "code"       VARCHAR(20)   NOT NULL,
        "position"   INTEGER       NOT NULL DEFAULT 0,
        "name"       VARCHAR(200)  NOT NULL,
        "price"      REAL          NOT NULL,
        "category"   VARCHAR(50)   NOT NULL DEFAULT 'food'
                     CHECK("category" IN ('food', 'essential')),
        "is_active"  INTEGER       NOT NULL DEFAULT 1,
        "created_at" DATETIME      NOT NULL DEFAULT (datetime('now')),
        "updated_at" DATETIME      NOT NULL DEFAULT (datetime('now')),
        CONSTRAINT "PK_menu_items_id" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_menu_items_code" UNIQUE ("code")
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "orders" (
        "id"                       VARCHAR(36)  NOT NULL,
        "service_date"             VARCHAR(20)  NOT NULL,
        "user_id"                  VARCHAR(36)  NOT NULL,
        "source"                   VARCHAR(30)  NOT NULL DEFAULT 'kiosk'
                                   CHECK("source" IN ('kiosk', 'counter', 'scan', 'order_form', 'scanner')),
        "sheet_id"                 VARCHAR(36),
        "status"                   VARCHAR(20)  NOT NULL DEFAULT 'pending'
                                   CHECK("status" IN ('pending', 'paid', 'delivered', 'rejected', 'superseded')),
        "total_amount"             REAL         NOT NULL DEFAULT 0,
        "payment_status"           VARCHAR(20)  NOT NULL DEFAULT 'unpaid'
                                   CHECK("payment_status" IN ('unpaid', 'paid')),
        "payment_method"           VARCHAR(50),
        "superseded_at"            DATETIME,
        "superseded_by_order_id"   VARCHAR(36),
        "settled_by_operator_id"   VARCHAR(36),
        "settled_at"               DATETIME,
        "reject_reason"            TEXT,
        "transfer_reference"       VARCHAR(255),
        "received_amount"          REAL,
        "created_at"               DATETIME     NOT NULL DEFAULT (datetime('now')),
        "updated_at"               DATETIME     NOT NULL DEFAULT (datetime('now')),
        CONSTRAINT "PK_orders_id" PRIMARY KEY ("id"),
        CONSTRAINT "FK_orders_user" FOREIGN KEY ("user_id")
          REFERENCES "users"("id") ON DELETE CASCADE
      )
    `);

    await queryRunner.query(`
      CREATE INDEX "IDX_orders_service_date" ON "orders" ("service_date")
    `);

    await queryRunner.query(`
      CREATE INDEX "IDX_orders_user_id" ON "orders" ("user_id")
    `);

    await queryRunner.query(`
      CREATE TABLE "order_items" (
        "id"           VARCHAR(36)  NOT NULL,
        "order_id"     VARCHAR(36)  NOT NULL,
        "menu_item_id" VARCHAR(36)  NOT NULL,
        "unit_price"   REAL         NOT NULL,
        "category"     VARCHAR(50)  NOT NULL DEFAULT 'food'
                       CHECK("category" IN ('food', 'essential')),
        "quantity"     INTEGER      NOT NULL DEFAULT 1,
        "created_at"   DATETIME     NOT NULL DEFAULT (datetime('now')),
        CONSTRAINT "PK_order_items_id" PRIMARY KEY ("id"),
        CONSTRAINT "FK_order_items_order" FOREIGN KEY ("order_id")
          REFERENCES "orders"("id") ON DELETE CASCADE,
        CONSTRAINT "FK_order_items_menu_item" FOREIGN KEY ("menu_item_id")
          REFERENCES "menu_items"("id") ON DELETE RESTRICT
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "order_tg8_documents" (
        "order_id"          VARCHAR(36) NOT NULL,
        "template_revision" INTEGER     NOT NULL,
        "snapshot"          TEXT        NOT NULL,
        "accepted_at"       DATETIME,
        "operator_id"       VARCHAR(36),
        "created_at"        DATETIME    NOT NULL DEFAULT (datetime('now')),
        CONSTRAINT "PK_order_tg8_documents" PRIMARY KEY ("order_id"),
        CONSTRAINT "FK_tg8_order" FOREIGN KEY ("order_id")
          REFERENCES "orders"("id") ON DELETE CASCADE
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "payment_config" (
        "id"             VARCHAR(36)  NOT NULL,
        "singleton"      INTEGER      NOT NULL DEFAULT 1 UNIQUE,
        "bank_bin"       VARCHAR(20),
        "account_number" VARCHAR(50),
        "account_name"   VARCHAR(200),
        "updated_at"     DATETIME     NOT NULL DEFAULT (datetime('now')),
        CONSTRAINT "PK_payment_config_id" PRIMARY KEY ("id")
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "purchase_limit_config" (
        "id"                        VARCHAR(36) NOT NULL,
        "singleton"                 INTEGER     NOT NULL DEFAULT 1 UNIQUE,
        "prisoner_food_enabled"     INTEGER     NOT NULL DEFAULT 0,
        "prisoner_food_amount"      REAL        NOT NULL DEFAULT 0,
        "prisoner_essential_enabled" INTEGER    NOT NULL DEFAULT 0,
        "prisoner_essential_amount" REAL        NOT NULL DEFAULT 0,
        "visitor_food_enabled"      INTEGER     NOT NULL DEFAULT 0,
        "visitor_food_amount"       REAL        NOT NULL DEFAULT 0,
        "visitor_essential_enabled" INTEGER     NOT NULL DEFAULT 0,
        "visitor_essential_amount"  REAL        NOT NULL DEFAULT 0,
        "updated_at"                DATETIME    NOT NULL DEFAULT (datetime('now')),
        CONSTRAINT "PK_purchase_limit_config_id" PRIMARY KEY ("id")
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "sync_runs" (
        "id"          VARCHAR(36)  NOT NULL,
        "started_at"  DATETIME     NOT NULL DEFAULT (datetime('now')),
        "finished_at" DATETIME,
        "row_count"   INTEGER      NOT NULL DEFAULT 0,
        "status"      VARCHAR(20)  NOT NULL DEFAULT 'running'
                      CHECK("status" IN ('running', 'success', 'failed')),
        "trigger"     VARCHAR(50),
        "error"       TEXT,
        "created_at"  DATETIME     NOT NULL DEFAULT (datetime('now')),
        CONSTRAINT "PK_sync_runs_id" PRIMARY KEY ("id")
      )
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS "sync_runs"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "purchase_limit_config"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "payment_config"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "order_tg8_documents"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "order_items"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "orders"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "menu_items"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "account_transactions"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "prisoner_accounts"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "users"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "operators"`);
  }
}
