import { INestApplication, ValidationPipe } from '@nestjs/common';
import { Test, TestingModule } from '@nestjs/testing';
import { DataSource } from 'typeorm';
import * as bcrypt from 'bcrypt';
import { AppModule } from '../../src/app.module';
import { AllExceptionsFilter } from '../../src/common/filters/all-exceptions.filter';
import { Operator, OperatorRole } from '../../src/operators/operator.entity';
import { BCRYPT_COST } from '../../src/operators/operator-public';
import { User } from '../../src/users/user.entity';
import { normalizeCell } from '../../src/users/cell-normalization';
import { MenuItem } from '../../src/menu/menu-item.entity';
import { ThresholdConfig } from '../../src/config/threshold-config.entity';
import { DEMO_ROI_TEMPLATE } from '../../src/database/seeds/demo-assets';
import { todayInDeployTz, tomorrowInDeployTz } from '../../src/common/today-in-tz';
import request from 'supertest';
import { randomUUID } from 'crypto';
import {
  IssuedOmrForm,
  IssuedOmrFormStatus,
} from '../../src/omr-forms/issued-omr-form.entity';
import {
  OmrFormMode,
  OmrFormOrientation,
  OmrFormTemplate,
} from '../../src/omr-forms/omr-form-template.entity';
import { canonicalGeometryHash } from '../../src/omr-forms/omr-form-templates.service';
import { Sheet } from '../../src/scans/sheet.entity';
import { MenuItemCategory } from '../../src/menu/menu-item-category.enum';
import { ConfigService } from '@nestjs/config';
import { configureRequestBodyParsers } from '../../src/main';
import type { NestExpressApplication } from '@nestjs/platform-express';

// Shared e2e bootstrap. Every spec builds the app the same way (same ValidationPipe +
// exception filter the production bootstrap uses) so request behaviour matches the live
// server. The session model is gone: there is one global menu and a single
// threshold_config row that owns the OMR form template, so the helpers below seed those
// two globals directly rather than creating a session.

export interface E2EContext {
  app: INestApplication;
  moduleRef: TestingModule;
  dataSource: DataSource;
}

export interface CreateAppOptions {
  // Hook to override providers (e.g. mock OmrClientService) before compile().
  configure?: (builder: ReturnType<typeof Test.createTestingModule>) => void;
}

// Builds and initialises a Nest app wired exactly like the production bootstrap.
export async function createE2EApp(options: CreateAppOptions = {}): Promise<E2EContext> {
  let builder = Test.createTestingModule({ imports: [AppModule] });
  if (options.configure) options.configure(builder);
  const moduleRef = await builder.compile();

  const app = moduleRef.createNestApplication<NestExpressApplication>();
  configureRequestBodyParsers(app, moduleRef.get(ConfigService));
  app.useGlobalPipes(
    new ValidationPipe({ whitelist: true, forbidNonWhitelisted: true, transform: true }),
  );
  app.useGlobalFilters(new AllExceptionsFilter());
  await app.init();

  const dataSource = moduleRef.get<DataSource>(DataSource);
  return { app, moduleRef, dataSource };
}

// The three global menu items every menu-dependent spec shares: positions 0,1,2, ascending
// prices. Returned in position order so specs can index by position.
export interface SeededMenuItem {
  id: string;
  position: number;
  name: string;
  price: number;
  category: MenuItemCategory;
}

export const GLOBAL_MENU = [
  { name: 'Com ga', price: 35_000, category: MenuItemCategory.FOOD },
  { name: 'Bun bo', price: 40_000, category: MenuItemCategory.FOOD },
  { name: 'Pho bo', price: 45_000, category: MenuItemCategory.ESSENTIAL },
] as const;

// Inserts the three global menu items at positions 0,1,2 directly (bypassing the admin HTTP
// path, which is exercised separately) so order/kiosk/counter specs have a stable menu.
export async function seedGlobalMenu(ds: DataSource): Promise<SeededMenuItem[]> {
  const repo = ds.getRepository(MenuItem);
  const rows = GLOBAL_MENU.map((m, i) =>
    repo.create({
      code: String(i + 1).padStart(2, '0'),
      name: m.name,
      price: m.price,
      category: m.category,
      position: i,
      isActive: true,
    }),
  );
  const saved = await repo.save(rows);
  return saved
    .map((m) => ({ id: m.id, position: m.position, name: m.name, price: m.price, category: m.category }))
    .sort((a, b) => a.position - b.position);
}

// Marks the global OMR form as generated by upserting the singleton threshold_config row with
// a ROI template + roiGeneratedAt stamp. This is the post-refactor equivalent of "open a
// session with a form": scans decode against this template, and menu rename/reorder/hard-delete
// lock once it is set. Uses the committed demo ROI (order-line code+qty boxes) so a mocked
// OMR processScan result aligns with the recognized order lines. The version must match the
// processor's expected ROI version or ingestion rejects the sheet (stored-template guard).
export async function generateGlobalForm(
  ds: DataSource,
  roiTemplate: object = DEMO_ROI_TEMPLATE,
  roiVersion = 'v3',
): Promise<void> {
  const repo = ds.getRepository(ThresholdConfig);
  let row = await repo.findOne({ where: {} });
  if (!row) {
    // Mirror the env defaults the lazy getGlobal() would seed; values are valid (empty<ticked).
    row = repo.create({
      icrThreshold: 0.85,
      omrEmptyMax: 0.3,
      omrTickedMin: 0.7,
      digitBoxCount: 6,
    });
  }
  row.roiTemplate = roiTemplate;
  row.roiVersion = roiVersion;
  row.roiGeneratedAt = new Date();
  await repo.save(row);
}

export interface SeedIssuedFormOptions {
  userId: string;
  issuedBy: string;
  serviceDate: string;
  token?: string;
  roiVersion?: string;
  status?: IssuedOmrFormStatus;
  reservedSheetId?: string | null;
  consumedSheetId?: string | null;
}

// Seeds the auditable bearer-token record at the persistence boundary. OMR processing tests
// use an unreserved form; confirm tests bind it to a pre-built FLAGGED sheet below.
export async function seedIssuedForm(
  ds: DataSource,
  options: SeedIssuedFormOptions,
): Promise<IssuedOmrForm> {
  const status = options.status ?? IssuedOmrFormStatus.ISSUED;
  const templateRepo = ds.getRepository(OmrFormTemplate);
  const geometryHash = canonicalGeometryHash(DEMO_ROI_TEMPLATE);
  let template = await templateRepo.findOne({ where: { geometryHash } });
  if (!template) {
    const revision = 'a4-code-v3';
    const revisionOwner = await templateRepo.findOne({ where: { revision } });
    if (revisionOwner) {
      throw new Error(`E2E template revision ${revision} is bound to different geometry`);
    }
    const now = new Date();
    template = await templateRepo.save(templateRepo.create({
      revision,
      mode: OmrFormMode.CODE,
      paperSize: 'A4',
      orientation: OmrFormOrientation.PORTRAIT,
      geometry: DEMO_ROI_TEMPLATE,
      geometryHash,
      catalogHash: null,
      isActive: false,
      activatedAt: now,
      retiredAt: now,
    }));
  }
  const repo = ds.getRepository(IssuedOmrForm);
  return repo.save(
    repo.create({
      token: options.token ?? randomUUID(),
      userId: options.userId,
      serviceDate: options.serviceDate,
      roiVersion: options.roiVersion ?? template.revision,
      templateId: template.id,
      formMode: template.mode,
      issuedBy: options.issuedBy,
      status,
      reservedSheetId: options.reservedSheetId ?? null,
      consumedSheetId: options.consumedSheetId ?? null,
      consumedAt: status === IssuedOmrFormStatus.CONSUMED ? new Date() : null,
      voidedAt: status === IssuedOmrFormStatus.VOID ? new Date() : null,
      voidReason: status === IssuedOmrFormStatus.VOID ? 'synthetic-e2e-void' : null,
    }),
  );
}

export async function bindIssuedFormToSheet(
  ds: DataSource,
  sheet: Sheet,
  options: Omit<SeedIssuedFormOptions, 'serviceDate' | 'reservedSheetId'>,
): Promise<IssuedOmrForm> {
  const form = await seedIssuedForm(ds, {
    ...options,
    serviceDate: sheet.serviceDate,
    reservedSheetId: sheet.id,
  });
  sheet.issuedFormId = form.token;
  sheet.matchedUserId = form.userId;
  sheet.recognizedId = null;
  await ds.getRepository(Sheet).save(sheet);
  return form;
}

// Clears the global form-generated signal so a spec can exercise the FORM_NOT_GENERATED path.
export async function clearGlobalForm(ds: DataSource): Promise<void> {
  const repo = ds.getRepository(ThresholdConfig);
  const row = await repo.findOne({ where: {} });
  if (!row) return;
  row.roiTemplate = null;
  row.roiVersion = null;
  row.roiGeneratedAt = null;
  await repo.save(row);
}

// Seeds an operator and returns it. Password is the shared E2E password.
export const E2E_PASSWORD = 'e2epass1234';

export async function seedOperator(
  ds: DataSource,
  username: string,
  role: OperatorRole,
  isActive = true,
): Promise<Operator> {
  const repo = ds.getRepository(Operator);
  return repo.save(
    repo.create({
      username,
      passwordHash: await bcrypt.hash(E2E_PASSWORD, BCRYPT_COST),
      displayName: username,
      role,
      isActive,
    }),
  );
}

// Logs an operator in via the HTTP path and returns the bearer token.
export async function login(app: INestApplication, username: string): Promise<string> {
  const res = await request(app.getHttpServer())
    .post('/auth/login')
    .send({ username, password: E2E_PASSWORD });
  return res.body.token as string;
}

// Seeds a user (prisoner). Defaults to active.
export async function seedUser(
  ds: DataSource,
  legacyId: string,
  name = `Inmate ${legacyId}`,
  isActive = true,
): Promise<User> {
  const repo = ds.getRepository(User);
  const normalizedCell = normalizeCell(null);
  return repo.save(
    repo.create({
      legacyId,
      name,
      zone: null,
      cell: null,
      normalizedCell: normalizedCell.value,
      cellNormalizationVersion: normalizedCell.version,
      isActive,
      source: 'test',
      syncedAt: new Date(),
    }),
  );
}

// Today's service_date in the deploy timezone.
export function today(): string {
  return todayInDeployTz();
}

// Tomorrow's service_date in the deploy timezone — the next collection day the app now
// stamps on every scan/order, and the day the collection dashboards default to.
export function tomorrow(): string {
  return tomorrowInDeployTz();
}

// Truncate helper: clears the mutable domain tables between specs. operators/users/menu are
// per-spec seeded, so each spec truncates exactly what it owns. CASCADE handles the FK web.
export async function truncate(ds: DataSource, tables: string[]): Promise<void> {
  if (tables.length === 0) return;
  await ds.query(`TRUNCATE TABLE ${tables.join(', ')} CASCADE`);
}
